### ISSUE TITLE
Exception on KDBX.build()

### ISSUE THREAD

**Issue by loupianche** [libkeepass/pykeepass#177]
ArchLinux, python-pykeepass 3.0.3-2

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/construct/lib/containers.py", line 100, in __getattr__
    return self[name]
KeyError: 'transformed_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/passbook/keepass_collection.py", line 162, in __save
    keyfile=self.__kp.keyfile)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 352, in build
    self.build_stream(obj, stream, **contextkw)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 364, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 2003, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 2472, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 3670, in _build
    return sc._build(obj, stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 2003, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 2472, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 2607, in _build
    return self.func(context) if callable(self.func) else self.func
  File "/usr/lib/python3.7/site-packages/pykeepass/kdbx_parsing/kdbx4.py", line 40, in compute_transformed
    if context._._.transformed_key is not None:
  File "/usr/lib/python3.7/site-packages/construct/lib/containers.py", line 102, in __getattr__
    raise AttributeError(name)
AttributeError: transformed_key
```

**Comment by Evidlo** [comment]
Test this on `HEAD`.

**Comment by loupianche** [comment]
Same error with python-pykeepass-git 3.0.3.r40.gab485d4-1

**Comment by Evidlo** [comment]
Can I get more detail?  Or a sample database that produces this issue?

**Comment by loupianche** [comment]
Freshly created kdbx with KeepassXC. Maybe it's related to some new python lib in ArchLinux.

[Mots de passe.zip](https://github.com/libkeepass/pykeepass/files/3732834/Mots.de.passe.zip)

**Comment by Evidlo** [comment]
What's the password/keyfile for this db?

**Comment by Evidlo** [comment]
@loupianche  bump

**Comment by loupianche** [comment]
linux

**Comment by Evidlo** [comment]
This seems to work fine on `3.1.1`.

``` 
[evan@blackbox downloads] pip freeze | grep pykeepass
pykeepass==3.1.1

[evan@blackbox downloads] ipython3
In [1]: from pykeepass import PyKeePass                                                         
In [2]: kp = PyKeePass('Mots de passe.kdbx', 'linux')                                           
In [3]: kp.entries
                                           
Out[3]: [Entry: "plop/mot de passe (coucou)"]
```

**Comment by bellegarde-c** [comment]
OK, so you can close, waiting for ArchLinux to update.
