### ISSUE TITLE
GNOME PasswordSafe won't work with pykeepass-3.1.1

### ISSUE THREAD

**Issue by okias** [libkeepass/pykeepass#180]
PasswordSafe won't work with pykeepass-3.1.1, works with 3.0.3.

After entering password into Safe, this trackeback comes.
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/passwordsafe/unlock_database.py", line 277, in password_unlock_success
    self.open_database_page()
  File "/usr/lib/python3.7/site-packages/passwordsafe/unlock_database.py", line 603, in open_database_page
    UnlockedDatabase(self.window, self.parent_widget, self.database_manager, self)
  File "/usr/lib/python3.7/site-packages/passwordsafe/unlocked_database.py", line 86, in __init__
    self.assemble_listbox()
  File "/usr/lib/python3.7/site-packages/passwordsafe/unlocked_database.py", line 132, in assemble_listbox
    self.show_page_of_new_directory(False, False)
  File "/usr/lib/python3.7/site-packages/passwordsafe/unlocked_database.py", line 242, in show_page_of_new_directory
    elif self.stack.get_child_by_name(self.database_manager.get_group_uuid_from_group_object(self.current_group)) is None and self.stack.get_child_by_name(self.database_manager.get_entry_uuid_from_entry_object(self.current_group)) is None and edit_group is False:
TypeError: Must be string, not UUID
```

**Comment by Evidlo** [comment]
This should probably be filed with PasswordSafe, as the exception is raised there.  

It's probably because `Entry.uuid` and `Group.uuid` return a `uuid.UUID` object now instead of a string.
