### ISSUE TITLE
Failing to install in tox environment

### ISSUE THREAD

**Issue by MoisMoshev** [libkeepass/pykeepass#236]
Hey, trying to install now for a python 3.8 environment when running tox tests, and getting this error

```
(path:C:\Users\mmoshev\AppData\Local\Temp\pip-install-vtkbgtqg\pykeepass\setup.py) egg_info for package pykeepass
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mmoshev\AppData\Local\Temp\pip-install-vtkbgtqg\pykeepass\setup.py", line 2, in <module>
        from pykeepass import __version__
      File "C:\Users\mmoshev\AppData\Local\Temp\pip-install-vtkbgtqg\pykeepass\pykeepass\__init__.py", line 2, in <module>
        from .pykeepass import PyKeePass, create_database
      File "C:\Users\mmoshev\AppData\Local\Temp\pip-install-vtkbgtqg\pykeepass\pykeepass\pykeepass.py", line 5, in <module>
        from future.utils import python_2_unicode_compatible
    ModuleNotFoundError: No module named 'future'
```

Aside from the fact that the future module is not found, it seems wrong to trigger such cascading imports just to get the version?

The environment installs its dependencies by
    install_command = pip install -v -i http://devpiserver/... --trusted-host ... {opts} {packages}

**Comment by Evidlo** [comment]
Maybe it's related to https://github.com/libkeepass/pykeepass/pull/213

**Comment by MoisMoshev** [comment]
Definitely sounds like it. Thanks I'll try the fork.
