### ISSUE TITLE
pykeepass 4.0: ValueError: PKCS#7 padding is incorrect.

### ISSUE THREAD

**Issue by jugmac00** [libkeepass/pykeepass#244]
I use `pykeepass` for my app `hibpcli` which checks passwords in a `keepass` db against the `haveibeenpwned` API.

https://github.com/jugmac00/hibpcli/

Since the update from `pykeepass` 3.2.1 to 4.0 I receive the following error:

`ValueError: PKCS#7 padding is incorrect.`

The error occurs in that line in my app:

```
PyKeePass(path, password=master_password)
```

The error only occurs with a **wrong** password!

The test db was created with keepassxc.

Please find attached the test db - password "test".

[test.zip](https://github.com/libkeepass/pykeepass/files/5939046/test.zip)

**minimal code to reproduce error**

correct password = works

```
>>> from pykeepass import PyKeePass
>>> p = PyKeePass("tests/test.kdbx", password="test")
```

wrong password - ValueError: Padding is incorrect.

```
>>> p = PyKeePass("tests/test.kdbx", password="ts")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 65, in __init__
    self.read(
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 103, in read
    self.kdbx = KDBX.parse_file(
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 309, in parse_file
    return self.parse_stream(f, **contextkw)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 3628, in _parse
    return sc._parsereport(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 697, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 3628, in _parse
    return sc._parsereport(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/construct/core.py", line 698, in _parse
    return self._decode(obj, context, path)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/pykeepass/kdbx_parsing/common.py", line 285, in _decode
    payload_data = self.unpad(payload_data)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/pykeepass/kdbx_parsing/common.py", line 306, in unpad
    return CryptoPadding.unpad(data, 16)
  File "/home/jugmac00/Projects/hibpcli/venv4/lib/python3.8/site-packages/Cryptodome/Util/Padding.py", line 90, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
```

With pykeepass 3.2.1 I received an `CredentialsError`, which I catch in my app.

This seems to be a regression from https://github.com/libkeepass/pykeepass/pull/212

**Comment by padmalcom** [comment]
This still exists when I create a new keystore using keepass 2.47 using a keyfile. The issue can be avoided by using pykeepass 3.2.1 and a version 1.x keyfile.

**Comment by jugmac00** [comment]
Thank you!

It would be awesome to have a new release with this fix.
