### ISSUE TITLE
Printing Keepass Entries causes Type Error when Title is None

### ISSUE THREAD

**Issue by blauertee** [libkeepass/pykeepass#250]
Just got started with pykeepass the first thing I did was this:

```p = '***'
path = '/path/to/file'
kpdb = PyKeePass(path, password=p)
for e in kpdb.entries:
    print(str(e))```


```
resulting in:

```
Entry: "..."
.
.
.
Entry: "..."
Traceback (most recent call last):
  File "/path/to/script.py", line 10, in <module>
    print(str(e))
  File "/path/to/lib/python3.7/site-packages/pykeepass/entry.py", line 294, in __str__
    pathstr = '/'.join(self.path)
TypeError: sequence item 1: expected str instance, NoneType found
```

Should be an easy Fix :)

**Comment by Evidlo** [comment]
This should be fixed with the latest commit.  Can you test it out?

**Comment by blauertee** [comment]
Yup works like a charm :)
