### ISSUE TITLE
Current method for enabling in-memory protection?

### ISSUE THREAD

**Issue by p-doyle** [libkeepass/pykeepass#253]
I found an old issue (#89) that mentioned how to enable in memory protection on an existing string field but it seems to be outdated and I was wondering if anyone could provide an updated method of doing this?

Windows 10
Keepass 4.0.0
Python 3.7

I tried the below code but just setting the attribute doesn't seem to actually encrypt the string and results in a corrupted database.
```
for e in kp.entries:
    if 'my_field' in e.custom_properties.keys():
        e._element.xpath('String/Key[text()="my_field"]/../Value')[0].attrib['Protected'] = "False"
kp.save()
```

When attempting to re-open the database it throws an exception when trying to decrypt the string:
```
Traceback (most recent call last):
  File "D:/KeepassTest.py", line 8, in <module>
    kp = PyKeePass('keepassdb.kdbx', password='password123')
  File "E:\Program Files\Python37\lib\site-packages\pykeepass\pykeepass.py", line 69, in __init__
    transformed_key=transformed_key
  File "E:\Program Files\Python37\lib\site-packages\pykeepass\pykeepass.py", line 107, in read
    transformed_key=transformed_key
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 309, in parse_file
    return self.parse_stream(f, **contextkw)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 3628, in _parse
    return sc._parsereport(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 698, in _parse
    return self._decode(obj, context, path)
  File "E:\Program Files\Python37\lib\site-packages\pykeepass\kdbx_parsing\common.py", line 76, in _decode
    return subcon_out.parse(data, **con)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 3628, in _parse
    return sc._parsereport(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "E:\Program Files\Python37\lib\site-packages\construct\core.py", line 698, in _parse
    return self._decode(obj, context, path)
  File "E:\Program Files\Python37\lib\site-packages\pykeepass\kdbx_parsing\common.py", line 191, in _decode
    result = cipher.decrypt(base64.b64decode(elem.text)).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 0: invalid continuation byte
```

I also can't seem to find the `kp.kdb.protect()` function mentioned in the old issue either and couldn't figure out how to encrypt the string manually...  Does anyone know how to do this?

One other unrelated thing I noticed is that the size of the database is reduced when saving, even if no changes were made, from 494kb to 404kb.  Is there some kind of optimization going on?  Just want to make sure I am not losing any information.

Thank you!

**Comment by mbirth** [comment]
This is what I'm using and it seems to work for me:

```python
key = "my secret item"
entry._element.xpath('String[Key[text()="{}"]]/Value'.format(key))[0].attrib["Protected"] = "True"
```

Basically you're just setting the XML attribute `Protected` for the `<Value>` node.

**Comment by p-doyle** [comment]
That works great!  The XML posted in #89 was slightly different and that was likely causing my issue.  Thanks!
