### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by tuk-solita** [libkeepass/pykeepass#263]
I'm trying to install the package with `pip install pykeepass`, but I get an error. Here is the installation log: 
```
$ pip install pykeepass
Collecting pykeepass
  Using cached https://files.pythonhosted.org/packages/f1/08/b4b8f7bce23190ed4f34f4d9cf4f75f8a255f4f4c378296daf4b7027d2cb/pykeepass-4.0.1.tar.gz
Collecting python-dateutil (from pykeepass)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting construct==2.10.54 (from pykeepass)
  Using cached https://files.pythonhosted.org/packages/30/2f/e2e6bad1b80f744cf5c2a6d622e3dee698b43e6c040f980ae0ac0edd5e54/construct-2.10.54.tar.gz
Collecting argon2_cffi (from pykeepass)
  Using cached https://files.pythonhosted.org/packages/a0/c6/420e3cfb7f162eb51dcfdb1c2d80e5baa522c743487937c17ae0d760dd19/argon2_cffi-20.1.0-cp37-cp37m-win_amd64.whl
Collecting pycryptodomex>=3.6.2 (from pykeepass)
  Using cached https://files.pythonhosted.org/packages/82/e2/a0f9f5452a59bafaa3420585f22b58a8566c4717a88c139af2276bb5695d/pycryptodomex-3.10.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\pip-install-_1mx45ke\\pycryptodomex\\setup.py'"'"'; __file__='"'"'C:\\Users\\MYUSERNAME\\AppData\\Local\\Temp\\pip-install-_1mx45ke\\pycryptodomex\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\MYUSERNAME\AppData\Local\Temp\pip-install-_1mx45ke\pycryptodomex\
    Complete output (31 lines):
    Testing support for clang
    Traceback (most recent call last):
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MYUSERNAME\AppData\Local\Temp\pip-install-_1mx45ke\pycryptodomex\setup.py", line 468, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\MYUSERNAME\AppData\Local\Temp\pip-install-_1mx45ke\pycryptodomex\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\MYUSERNAME\AppData\Local\Temp\pip-install-_1mx45ke\pycryptodomex\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\MYUSERNAME\AppData\Local\Temp\pip-install-_1mx45ke\pycryptodomex\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\python37\lib\distutils\_msvccompiler.py", line 318, in compile
        self.initialize()
      File "c:\python37\lib\distutils\_msvccompiler.py", line 215, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
Versions
```
$ python -V
Python 3.7.7

$ pip -V
pip 19.2.3 from c:\python37\lib\site-packages\pip (python 3.7)
```

**Comment by dieser-niko** [comment]
https://stackoverflow.com/a/44953739
This might help you (don't be confused, this error also occurs on other packages)

**Comment by Evidlo** [comment]
Yep, install the build tools from Microsoft.

**Comment by tuk-solita** [comment]
Okay. Thanks. I also managed to install pykeepass by installing specific versions: `pip install pycryptodome==3.9.0` & `pip install pykeepass==3.1.1`.
