### ISSUE TITLE
Error parsing path on a virtual filesystem

### ISSUE THREAD

**Issue by A6GibKm** [libkeepass/pykeepass#266]
when trying to `save` on a virtual filesystem on a Flatpak environment 
I get an error of type `construct.core.StreamError` with message `Error in path (building) -> header`. The path of such file is of the form
```
/run/user/1000/gvfs/google-drive:host=domain.com,user=xxxxxx/aosifj--IDAKSK/ASNsakdsuMOS_asoiamaoSKFN
```

**Comment by Evidlo** [comment]
You can test if this is an error in Construct

``` python
from construct import Struct, Bytes
s = Struct("field1" / Bytes(16))
parsed = s.parse(b'\x00' * 16)

s.build_file(parsed, '/path/to/file')
parsed = s.parse_file('/path/to/file')
```

**Comment by A6GibKm** [comment]
I run that with a path `/run/user/1000/doc/4a590d6a/1Ok2JCH6OhZBMia1tSPo6CDnPuMXONhrG`

```
>>> s.build_file(parsed, path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/lib/python3.9/site-packages/construct/core.py", line 355, in build_file
    self.build_stream(obj, f, **contextkw)
OSError: [Errno 29] Illegal seek
```
As a side effect the database gets deleted (weights 0 bytes).

**Comment by spaetz** [comment]
This should have been fixed with the closing of https://github.com/libkeepass/pykeepass/pull/280 in 2022. Can we close this issue then too?

**Comment by Evidlo** [comment]
#280 fixes database corruption, but I think this is about what we should do (if anything) if seeking isn't supported.
