### ISSUE TITLE
Can't import on M1 Mac

### ISSUE THREAD

**Issue by rkhwaja** [libkeepass/pykeepass#270]
I get the following
```
>>> import pykeepass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.9/site-packages/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass, create_database
  File ".../lib/python3.9/site-packages/pykeepass/pykeepass.py", line 23, in <module>
    from pykeepass.kdbx_parsing.kdbx import KDBX
  File ".../lib/python3.9/site-packages/pykeepass/kdbx_parsing/__init__.py", line 1, in <module>
    from .kdbx import KDBX
  File ".../lib/python3.9/site-packages/pykeepass/kdbx_parsing/kdbx.py", line 4, in <module>
    from .kdbx4 import DynamicHeader as DynamicHeader4
  File ".../lib/python3.9/site-packages/pykeepass/kdbx_parsing/kdbx4.py", line 6, in <module>
    import argon2
  File ".../lib/python3.9/site-packages/argon2/__init__.py", line 5, in <module>
    from . import exceptions, low_level
  File ".../lib/python3.9/site-packages/argon2/low_level.py", line 17, in <module>
    from ._ffi import ffi, lib
ImportError: dlopen(.../lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: .../lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
  Expected in: flat namespace
 in .../lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
```

**Comment by Evidlo** [comment]
Maybe report this to https://github.com/hynek/argon2-cffi/ ?
