### ISSUE TITLE
Tests fail on big-endian platform (s390x)

### ISSUE THREAD

**Issue by musicinmybrain** [libkeepass/pykeepass#332]
Discovered in Fedora Linux.

```
+ /usr/bin/python3 -m unittest discover -s tests -v
tests (unittest.loader._FailedTest.tests) ... ERROR
======================================================================
ERROR: tests (unittest.loader._FailedTest.tests)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/usr/lib64/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/builddir/build/BUILD/pykeepass-4.0.3/tests/tests.py", line 18, in <module>
    from pykeepass import PyKeePass, icons
  File "/builddir/build/BUILD/pykeepass-4.0.3/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass, create_database
  File "/builddir/build/BUILD/pykeepass-4.0.3/pykeepass/pykeepass.py", line 28, in <module>
    from pykeepass.kdbx_parsing.kdbx import KDBX
  File "/builddir/build/BUILD/pykeepass-4.0.3/pykeepass/kdbx_parsing/__init__.py", line 1, in <module>
    from .kdbx import KDBX
  File "/builddir/build/BUILD/pykeepass-4.0.3/pykeepass/kdbx_parsing/kdbx.py", line 2, in <module>
    from .kdbx3 import DynamicHeader as DynamicHeader3
  File "/builddir/build/BUILD/pykeepass-4.0.3/pykeepass/kdbx_parsing/kdbx3.py", line 10, in <module>
    from .common import (
  File "/builddir/build/BUILD/pykeepass-4.0.3/pykeepass/kdbx_parsing/common.py", line 2, in <module>
    from .twofish import Twofish
  File "/builddir/build/BUILD/pykeepass-4.0.3/pykeepass/kdbx_parsing/twofish.py", line 27, in <module>
    from . import pytwofish
  File "/builddir/build/BUILD/pykeepass-4.0.3/pykeepass/kdbx_parsing/pytwofish.py", line 395, in <module>
    assert b'l\xb4V\x1c@\xbf\n\x97\x05\x93\x1c\xb6\xd4\x08\xe7\xfa' == Twofish(__testkey).encrypt(__testdat)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
----------------------------------------------------------------------
Ran 1 test in 0.000s
FAILED (errors=1)
```

For now, we will simply exclude that architecture; the only dependent package [already does so](https://src.fedoraproject.org/rpms/secrets/blob/e31477918101de297a36372281fe12de4a9fe259/f/secrets.spec#_15) for other reasons.

**Comment by musicinmybrain** [comment]
As far as I can tell in a very cursory review of `pykeepass/kdbx_parsing/pytwofish.py`, the use of explicitly little-endian `struct` format strings already covers the necessary byte-swapping, and the machinery conditionalized on `WORD_BIGENDIAN` is introducing an incorrect additional byte-swap operation. If I remove `WORD_BIGENDIAN` entirely (or, for a quick test, set it to `0` even when `sys.byteorder == 'big'` is `True`), then the tests pass on `s390x`. I’ve confirmed this both in `qemu-user-static` emulation and on real hardware.
